### ISSUE TITLE
First release road map

### ISSUE THREAD

**Issue by joeLepper** [joeLepper/whom#19]
What we are building here initially is a tool for the development of branched conversations.

The idea I have in mind requires me (and my collaborators) to write a fairly complex branched conversation. For the initial release we will want to be able to:

- [x] create a new story
- [x] save a story
- [x] load a story
- [x] save a story as
- [x] edit a story
- [x] add branches into a story
- [x] add "adopted" links into a story to create "merges" by clicking-and-dragging between nodes while editing
- [x] zoom in and out of a story

**Comment by joeLepper** [comment]
I think that we have enough to start going after an initial release.
